source 'https://rubygems.org'

gem 'bourbon'
gem 'dotenv-rails'
gem 'haml'
gem 'httparty'
gem 'hyperclient'
gem 'newrelic_rpm'
gem 'rake'
gem 'sass'
gem 'sinatra', '~> 4.0.0'
gem 'sinatra-assetpack', '>= 0.3.3', require: 'sinatra/assetpack'
gem 'sinatra-contrib', '>= 4.0.0'
gem 'unicorn'
gem 'useragent'
gem 'rack-timeout', '=0.1.0beta3'
gem 'redis-sinatra'
gem 'git'
gem 'app-version', git: 'git@github.com:VodafoneAustralia/app-version-gem.git'

group :development, :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'jasmine', '2.0.0.rc4'
  gem 'jmeter-runner-gem', git: 'git@github.com:VodafoneAustralia/jmeter-runner-gem.git'
  gem 'jshintrb'
  gem 'pact', git: 'git@github.com:realestate-com-au/pact.git'
  gem 'poltergeist'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-rescue'
  gem 'rack-test'
  gem 'rb-fsevent'
  gem 'rspec'
  gem 'rspec-html-matchers'
  gem 'shotgun'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'webmock'
end
