module StatusStrings

  #Fulfilment item statuses
  IS_SHIPPED = 'SHIPPED'
  IS_CANCELLED = 'CANCELLED'
  IS_BACKORDERED = 'BACKORDERED'
  IS_PROGRESS = 'IN PROGRESS'

  #Fulfilment tracking statuses
  TS_SHIPPED = 'SHIPPED'
  TS_PARTIALLY_SHIPPED = 'PARTIALLY SHIPPED'
  TS_CANCELLED = 'CANCELLED'
  TS_BACKORDERED = 'BACKORDERED'
  TS_PROGRESS = 'IN PROGRESS'
end